export default {
  ProfileTitle: 'Profile',
  ProfileBtn: 'Update',
  BillTitle: 'Bill',
  Bill_BillTitle: 'Currency account',
  Bill_CurrenciesTitle: 'Exchange Rates',
  Bill_Currency: 'Currency',
  Bill_Rate: 'Rate',
  Bill_Date: 'Date',
  HistoryTitle: 'Record history',
  History_Amount: 'Amount',
  History_Date: 'Date',
  History_Category: 'Category',
  History_Type: 'Type',
  History_Open: 'Open',
  EmptyHistory: 'There is nothing in history.',
  EmptyHistory_Link: 'Add new record',
  PlanningTitle: 'Planning',
  PlanningRemainder: ' left',
  PlanningExcess: 'Excess by ',
  RecordTitle: 'New Record',
  Record_Category: 'Select a category',
  RecordBtn: 'Create',
  CategoriesTitle: 'Categories',
  Categories_CreateTitle: 'Create',
  Categories_CreateBtn: 'Create',
  Categories_EditTitle: 'Edit',
  Categories_EditBtn: 'Update',
  Categories_Select: 'Select a category',
  Categories_No: 'No categories yet',
  Detail_BreadcrumbRoot: 'History',
  Detail_Descr: 'Description:',
  Detail_Amount: 'Amount:',
  Detail_Category: 'Category:',
  DetailNotFound: 'Record could not be found.',
  DetailNotFound_Link: 'Back to history page',
  LoginTitle: 'Home bookkeeping',
  LoginBtn: 'Sign in',
  RegisterTitle: 'Home bookkeeping',
  RegisterBtn: 'Sign up',
  Register_Rules: 'I agree with the rules',
  Register_RulesError: 'Check the box to continue',
  Menu_Bill: 'Bill',
  Menu_History: 'History',
  Menu_Planning: 'Planning',
  Menu_Record: 'New record',
  Menu_Categories: 'Categories',
  User_Profile: 'Profile',
  User_Logout: 'Logout',
  NoCategories: "You don't have any categories yet.",
  NoCategories_Link: 'Add new category',
  NoAccount: "Don't have an account?",
  NoAccount_Link: 'Sign up',
  haveAccount: 'Already have an account?',
  haveAccount_Link: 'Sign in!',
  Income: 'Income',
  Outcome: 'Outcome',
  PaginationNext: 'Next',
  PaginationPrev: 'Previous',
  Input_Amount: 'Amount',
  Input_Name: 'Name',
  Input_Descr: 'Description',
  Input_Limit: 'Limit',
  Input_Password: 'Password',
  Input_Category: 'Title',
  ErrorInputReq_Name: 'Enter name',
  ErrorInputUncorrect_Name: 'Enter correct name',
  ErrorInputMin_Amount: 'Minimum value is',
  ErrorInputReq_Descr: 'Enter a small description',
  ErrorInputReq_Category: 'Enter title',
  ErrorInputMin_Limit: 'Minimum value is',
  ErrorInputReq_Email: 'Enter Email',
  ErrorInputUncorrect_Email: 'Enter correct Email',
  ErrorInputReq_Password: 'Enter password',
  ErrorInputMin_Password_1: 'Must be at least',
  ErrorInputMin_Password_2: 'characters. Now',
  Message_default: 'Something went wrong',
  Message_logout: 'You are logged out',
  Message_login: 'Sign in, please',
  'Message_auth/wrong-password': 'You entered an incorrect password',
  'Message_auth/user-not-found': 'User with this email does not exist',
  'Message_auth/email-already-in-use': 'User with this email already exists',
  'Message_auth/network-request-failed': 'Failed to connect to server. Check your internet connection',
  ErrorMessageTitle: '[Error]:',
  Message_RecordAdded: 'Record added successfully',
  Message_InsufficientFunds: 'Insufficient funds. Missing',
  Message_CategoryAdded: 'Category successfully created',
  Message_CategoryUpdated: 'Category successfully updated'
}
