export default {
  ProfileTitle: 'Профиль',
  ProfileBtn: 'Обновить',
  BillTitle: 'Счет',
  Bill_BillTitle: 'Счет в валюте',
  Bill_CurrenciesTitle: 'Курс валют',
  Bill_Currency: 'Валюта',
  Bill_Rate: 'Курс',
  Bill_Date: 'Дата',
  HistoryTitle: 'История записей',
  History_Amount: 'Сумма',
  History_Date: 'Дата',
  History_Category: 'Категория',
  History_Type: 'Тип',
  History_Open: 'Открыть',
  EmptyHistory: 'В истории ничего нет.',
  EmptyHistory_Link: 'Добавить новую запись',
  PlanningTitle: 'Планирование',
  PlanningRemainder: 'Осталось ',
  PlanningExcess: 'Превышение на ',
  RecordTitle: 'Новая запись',
  Record_Category: 'Выберите категорию',
  RecordBtn: 'Создать',
  CategoriesTitle: 'Категории',
  Categories_CreateTitle: 'Создать',
  Categories_CreateBtn: 'Создать',
  Categories_EditTitle: 'Редактировать',
  Categories_EditBtn: 'Обновить',
  Categories_Select: 'Выберите категорию',
  Categories_No: 'Категорий пока нет',
  Detail_BreadcrumbRoot: 'История',
  Detail_Descr: 'Описание:',
  Detail_Amount: 'Сумма:',
  Detail_Category: 'Категория:',
  DetailNotFound: 'Не удалось найти запись',
  DetailNotFound_Link: 'Обратно на страницу истории',
  LoginTitle: 'Домашняя бухгалтерия',
  LoginBtn: 'Войти',
  RegisterTitle: 'Домашняя бухгалтерия',
  RegisterBtn: 'Зарегистрироваться',
  Register_Rules: 'С правилами согласен',
  Register_RulesError: 'Поставьте галочку, чтобы продолжить',
  Menu_Bill: 'Счет',
  Menu_History: 'История',
  Menu_Planning: 'Планирование',
  Menu_Record: 'Новая запись',
  Menu_Categories: 'Категории',
  User_Profile: 'Профиль',
  User_Logout: 'Выйти',
  NoCategories: 'У вас еще нет ни одной категории.',
  NoCategories_Link: 'Добавить новую категорию',
  NoAccount: 'Нет аккаунта?',
  NoAccount_Link: 'Зарегистрироваться',
  haveAccount: 'Уже есть аккаунт?',
  haveAccount_Link: 'Войти!',
  Income: 'Доход',
  Outcome: 'Расход',
  PaginationNext: 'Вперед',
  PaginationPrev: 'Назад',
  Input_Amount: 'Сумма',
  Input_Name: 'Имя',
  Input_Descr: 'Описание',
  Input_Limit: 'Лимит',
  Input_Password: 'Пароль',
  Input_Category: 'Название',
  ErrorInputReq_Name: 'Введите имя',
  ErrorInputUncorrect_Name: 'Введите корректное имя',
  ErrorInputMin_Amount: 'Минимальное значение',
  ErrorInputReq_Descr: 'Введите небольшое описание',
  ErrorInputReq_Category: 'Введите название',
  ErrorInputMin_Limit: 'Минимальная величина',
  ErrorInputReq_Email: 'Введите Email',
  ErrorInputUncorrect_Email: 'Введите корректный Email',
  ErrorInputReq_Password: 'Введите пароль',
  ErrorInputMin_Password_1: 'Должно быть не меньше',
  ErrorInputMin_Password_2: 'символов. Сейчас',
  Message_default: 'Что-то пошло не так',
  Message_logout: 'Вы вышли из системы',
  Message_login: 'Войдите в систему',
  'Message_auth/wrong-password': 'Вы ввели неверный пароль',
  'Message_auth/user-not-found': 'Пользователя с таким email не существует',
  'Message_auth/email-already-in-use': 'Пользователь с таким email уже существует',
  'Message_auth/network-request-failed': 'Не удалось подключиться к серверу. Проверьте подключение к интернету',
  ErrorMessageTitle: '[Ошибка]:',
  Message_RecordAdded: 'Запись успешно добавлена',
  Message_InsufficientFunds: 'Недостаточно средств. Не хватает',
  Message_CategoryAdded: 'Категория успешно создана',
  Message_CategoryUpdated: 'Категория успешно обновлена'
}
